# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

resources:
  - repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build, Test, Checkstyle, Docker
    jobs:
      - job: Build
        displayName: Build and Test
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self

          # Setup JDK
          - task: JavaToolInstaller@0
            inputs:
              versionSpec: '17'
              jdkArchitectureOption: 'x64'
              jdkSourceOption: 'PreInstalled'

          # Run Checkstyle
          - script: |
              ./gradlew checkstyleMain checkstyleTest
            displayName: Run Checkstyle analysis

          # Run unit tests
          - script: |
              ./gradlew clean test
            displayName: Run unit tests

          # Build Docker image
          - task: Docker@2
            displayName: Build Docker image
            inputs:
              command: build
              dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
              tags: |
                $(imageName):$(tag)
                $(imageName):latest
