# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

resources:
  - repo: self

variables:
  tag: '$(Build.BuildId)'

stages:

  # -------------------------------
  # Stage 1: Initialize
  # -------------------------------
  - stage: Initialize
    displayName: Initialize Environment
    jobs:
      - job: Setup
        displayName: Setup JDK
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self
          - task: JavaToolInstaller@0
            inputs:
              versionSpec: '17'
              jdkArchitectureOption: 'x64'
              jdkSourceOption: 'PreInstalled'

  # -------------------------------
  # Stage 2: Build
  # -------------------------------
  - stage: Build
    displayName: Build and Test
    dependsOn: Initialize
    jobs:
      # Checkstyle job
      - job: Checkstyle
        displayName: Run Checkstyle
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self
          - script: |
              ./gradlew checkstyleMain checkstyleTest
            displayName: Run Checkstyle analysis

      # Unit test job
      - job: UnitTest
        displayName: Run Unit Tests
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self
          - script: |
              ./gradlew clean test
            displayName: Run Unit Tests

  # -------------------------------
  # Stage 3: Deploy
  # -------------------------------
  - stage: Deploy
    displayName: Build Docker Image
    dependsOn: Build
    jobs:
      - job: DockerBuild
        displayName: Build Docker Image
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self

          - task: Docker@2
            displayName: Build Docker image
            inputs:
              command: build
              dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
              tags: |
                $(imageName):$(tag)
                $(imageName):latest
