-- If Flyway fails with the error "no schema has been selected to create in", it means your user does not have
-- permission to access the `public` schema. You should create your own schema (e.g., gamestore) and grant the
-- user access for production use.
-- CREATE SCHEMA IF NOT EXISTS gamestore AUTHORIZATION gamestorepostgresql_militarymy;
create table if not exists product (
    id bigint generated by default as identity,
    image varchar(255),
    price float8 not null,
    product_name varchar(255),
    primary key (id)
);
