/* uncomment for initialization */
create table product (
    id bigint generated by default as identity,
    image varchar(255),
    price float8 not null,
    product_name varchar(255),
    primary key (id)
);
